# Generated by Django 5.0.1 on 2024-01-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.CharField(max_length=4)),
                ('duracao', models.CharField(max_length=15)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('imagem', models.ImageField(upload_to='movie_images/')),
            ],
        ),
    ]
