# Generated by Django 5.0.1 on 2024-01-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_remove_categoria_filmes_remove_subcategoria_filmes'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='categoria',
            field=models.ManyToManyField(to='categoria.categoria'),
        ),
        migrations.AddField(
            model_name='filme',
            name='status',
            field=models.CharField(blank=True, choices=[('não visto', 'não visto'), ('visto', 'visto')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='subCategoria',
            field=models.ManyToManyField(to='categoria.subcategoria'),
        ),
    ]
