# Generated by Django 5.0.1 on 2024-01-10 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_remove_categoria_filmes_remove_subcategoria_filmes'),
        ('movie', '0002_filme_categoria_filme_status_filme_subcategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='subCategoria',
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='group_images/')),
                ('categoria', models.ManyToManyField(related_name='categoria', to='categoria.categoria')),
                ('subCategoria', models.ManyToManyField(related_name='subcategoria', to='categoria.subcategoria')),
            ],
        ),
        migrations.AddField(
            model_name='filme',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.grupo'),
        ),
    ]
