# Generated by Django 5.0.1 on 2024-01-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_filme_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='descricao',
            field=models.CharField(default='fghjkl', max_length=500),
            preserve_default=False,
        ),
    ]
